module FunctionAccessConstant

  # Function access master data
  FA_MST_BRAND = "FA_MST_BRAND"
  FA_MST_VENDOR = "FA_MST_VENDOR"
  FA_MST_SITE_STAT = "FA_MST_SITE_STAT"
  FA_MST_PROJECT = "FA_MST_PROJECT"

  # Function access site data
  FA_LOC_DEPARTMENT = "FA_LOC_DEPARTMENT"
  FA_LOC_SITE_GROUP = "FA_LOC_SITE_GROUP"
  FA_LOC_SITE = "FA_LOC_SITE"

  # Function access asset and component
  FA_ASS_COM_SOFTWARE = "FA_ASS_COM_SOFTWARE"
  FA_ASS_COM_COMPONENT_TYPE = "FA_ASS_COM_COMPONENT_TYPE"
  FA_ASS_COM_COMPONENT = "FA_ASS_COM_COMPONENT"
  FA_ASS_COM_ASSET_TYPE = "FA_ASS_COM_ASSET_TYPE"

  freeze
end