module FunctionAccessConstant

  FA_MST_BRAND = "FA_MST_BRAND"
  FA_MST_VENDOR = "FA_MST_VENDOR"
  FA_MST_SITE_STAT = "FA_MST_SITE_STAT"
  FA_MST_PROJECT = "FA_MST_PROJECT"

  FA_DEPARTMENT = "FA_DEPARTMENT"

  freeze
end