module FunctionAccessConstant
  # ASSET MANAGEMENT
  FA_ASSMGMT_DATA_ASSET = "FA_ASSMGMT_DATA_ASSET"
  FA_ASSMGMT_USER_ASSET = "FA_ASSMGMT_USER_ASSET"
  FA_ASSMGMT_ASSET_LOCATION = "FA_ASSMGMT_ASSET_LOCATION"
  FA_ASSMGMT_ASSET_SOFTWARE = "FA_ASSMGMT_ASSET_SOFTWARE"

  # FINANCE MANAGEMENT
  FA_FINMGMT_CP = "FA_FINMGMT_CP"
  FA_FINMGMT_RFP = "FA_FINMGMT_RFP"
  FA_FINMGMT_PO = "FA_FINMGMT_PO"
  FA_FINMGMT_DO = "FA_FINMGMT_DO"

  # INVENTORY MANAGEMENT
  FA_INVMGMT_DATA_INVENTORY = "FA_INVMGMT_DATA_INVENTORY"
  FA_INVMGMT_INVENTORY_LOCACTION = "FA_INVMGMT_INVENTORY_LOCACTION"

  # SETTINGS
  FA_SET_SITE_GROUP = "FA_SET_SITE_GROUP"
  FA_SET_SITE = "FA_SET_SITE"
  FA_SET_SITE_DEFAULT = "FA_SET_SITE_DEFAULT"
  FA_SET_ASSET_ITEM_TYPE = "FA_SET_ASSET_ITEM_TYPE"
  FA_SET_ASSET_MODEL = "FA_SET_ASSET_MODEL"
  FA_SET_COMPONENT = "FA_SET_COMPONENT"

  # MASTERS
  FA_MST_BRAND = "FA_MST_BRAND"
  FA_MST_VENDOR = "FA_MST_VENDOR"
  FA_MST_SITE_STAT = "FA_MST_SITE_STAT"
  FA_MST_ASS_SCHEDULE = "FA_MST_ASS_SCHEDULE"
  FA_MST_STORAGE_UNIT = "FA_MST_STORAGE_UNIT"
  FA_MST_PROJECT = "FA_MST_PROJECT"
  FA_MST_DEPARTMENT = "FA_MST_DEPARTMENT"
  FA_MST_ASSET_TYPE = "FA_MST_ASSET_TYPE"
  FA_MST_COMPONENT_TYPE = "FA_MST_COMPONENT_TYPE"
  FA_MST_SOFTWARE = "FA_MST_SOFTWARE"

  # ACCESS MANAGEMENT
  FA_ACCMGMT_ROLE = "FA_ACCMGMT_ROLE"
  FA_ACCMGMT_ACCOUNT = "FA_ACCMGMT_ACCOUNT"

  freeze
end
