default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
development:
  <<: *default
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: fus_ams_development
  
test:
  <<: *default
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  database: fus_ams_test
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["POSTGRES_HOST"] %>
    port: <%= ENV["POSTGRES_PORT"] %>
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    database: <%= ENV["POSTGRES_DB"] %>
  cache:
    <<: *primary_production
    database: fus_ams_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: fus_ams_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: fus_ams_production_cable
    migrations_paths: db/cable_migrate
