default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  
development:
  primary: &primary_development
    <<: *default
    database: fus_ams_development

  cache:
    <<: *primary_development
    database: fus_ams_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: fus_ams_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: fus_ams_development_cable
    migrations_paths: db/cable_migrate
  
test:
  primary: &primary_test
    <<: *default
    database: fus_ams_test

  cache:
    <<: *primary_test
    database: fus_ams_test_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_test
    database: fus_ams_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_test
    database: fus_ams_test_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["POSTGRES_HOST"] %>
    port: <%= ENV["POSTGRES_PORT"] %>
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    database: <%= ENV["POSTGRES_DB"] %>
  cache:
    <<: *primary_production
    database: fus_ams_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: fus_ams_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: fus_ams_production_cable
    migrations_paths: db/cable_migrate
